from pathlib import Path

def replace(path,old,new):
 p=Path(path);s=p.read_text();assert s.count(old)==1,(path,s.count(old));p.write_text(s.replace(old,new,1))

replace('main/power/sleep_service.cc','#include <esp_sleep.h>','#include <esp_sleep.h>\n#include <iot_button.h>')
replace('main/power/sleep_service.h','bool blocked_=false;','bool blocked_=false,buttons_paused_=false;')
replace('main/power/sleep_service.cc','bool SleepService::RestorePeripherals(){','bool SleepService::RestorePeripherals(){\n    if(buttons_paused_ && iot_button_resume()==ESP_OK)buttons_paused_=false;')
replace('main/power/sleep_service.cc','const bool ok=!audio_suspended_&&!radio_suspended_&&!pa_changed_;','const bool ok=!audio_suspended_&&!radio_suspended_&&!pa_changed_&&!buttons_paused_;')
replace('main/power/sleep_service.cc','if(audio_suspended_||radio_suspended_||pa_changed_){','if(audio_suspended_||radio_suspended_||pa_changed_||buttons_paused_){')
replace('main/power/sleep_service.cc','    const bool host=usb_serial_jtag_is_connected();','    // Native BLE is an experimental, separately budgeted mode: lock only.\n#if CONFIG_WHITEAI_EXPERIMENTAL_BLE_DISCOVERY\n    return;\n#endif\n    const bool host=usb_serial_jtag_is_connected();')
replace('main/power/sleep_service.cc','    esp_err_t err=gpio_wakeup_enable(POWER_BUTTON_GPIO,GPIO_INTR_LOW_LEVEL);','    // A 5 ms button timer must not replay thousands of missed callbacks.\n    // Pause only across actual CPU sleep; GPIO level remains our wake source.\n    esp_err_t err=iot_button_stop();\n    if(err!=ESP_OK){Gate::Instance().Thaw();Unlock("按键暂停失败，未进入休眠");return;}\n    buttons_paused_=true;\n    err=gpio_wakeup_enable(POWER_BUTTON_GPIO,GPIO_INTR_LOW_LEVEL);')
replace('main/power/sleep_service.cc','    const auto cause=esp_sleep_get_wakeup_cause();','    const auto cause=esp_sleep_get_wakeup_cause();\n    if(cause==ESP_SLEEP_WAKEUP_GPIO){key_woke_.store(true);suppress_click_until_.store(esp_timer_get_time()/1000+1000);}\n    const auto button_error=iot_button_resume();\n    if(button_error==ESP_OK)buttons_paused_=false;\n    else if(err==ESP_OK)err=button_error;')
replace('components/esp-wifi-connect/wifi_station.cc','    if(this_->sleeping_.load())return;\n    auto* event = static_cast<ip_event_got_ip_t*>(event_data);\n    std::lock_guard<std::recursive_mutex> state_lock(this_->state_mutex_);','    auto* event = static_cast<ip_event_got_ip_t*>(event_data);\n    std::lock_guard<std::recursive_mutex> state_lock(this_->state_mutex_);\n    if(this_->sleeping_.load())return;')
replace('components/esp-wifi-connect/wifi_station.cc','        if (SetupBusy()) return false;','        if (SetupBusy() || sleeping_.load()) return false;')
replace('tools/tests/sleep_stubs/platform.h','inline int pending=0,','inline bool buttons=false; inline int button_stop_error=0,button_resume_error=0;\ninline int pending=0,')
replace('tools/tests/sleep_stubs/platform.h','inline void Reset(){us+=1000000000;','inline void Reset(){buttons=false;button_stop_error=button_resume_error=0;us+=1000000000;')
replace('tools/tests/sleep_stubs/platform.h','inline int gpio_get_level(int){','inline int iot_button_stop(){if(sim::button_stop_error)return sim::button_stop_error;sim::buttons=true;return 0;}\ninline int iot_button_resume(){if(sim::button_resume_error)return sim::button_resume_error;sim::buttons=false;return 0;}\ninline int gpio_get_level(int){')
replace('tools/tests/sleep_stubs/platform.h','assert(sim::paused && sim::audio','assert(sim::buttons && sim::paused && sim::audio')
replace('tools/tests/sleep_contract.cc','    sim::Reset();sim::wifi=false;before=','    sim::Reset();sim::button_stop_error=-5;lock();tick();assert(!power::Locked()&&!sim::buttons&&!sim::paused);\n    sim::Reset();sim::button_resume_error=-6;lock();tick();assert(!power::Locked()&&sim::buttons);sim::button_resume_error=0;sim::us+=6000000;tick();assert(!sim::buttons);\n    sim::Reset();sim::usb=true;lock();tick();sim::resume_ok=false;unlock();assert(sim::paused);sim::resume_ok=true;sim::us+=6000000;tick();assert(!sim::paused);\n    sim::Reset();sim::usb=true;lock();tick();sim::codec_ok=false;unlock();assert(sim::audio&&!sim::pa);sim::codec_ok=true;sim::us+=6000000;tick();assert(!sim::audio&&sim::pa);\n    sim::Reset();sim::wifi=false;before=')
Path('tools/tests/sleep_stubs/iot_button.h').write_text('#pragma once\n#include "platform.h"\n')

replace('tools/check_volume_callbacks.py','#include "ui_work_queue.h"','#include "ui_work_queue.h"\n#include "power/activity.h"')

replace('tools/check_volume_callbacks.py','    std::puts("Volume callbacks OK:','    // Lock after an event is enqueued: even stale queued volume work must\n    // not enable audio or touch NVS behind the sleep coordinator.\n    for (auto action : {b.up.click,b.down.click,b.up.long_press,b.down.long_press}) {\n        const int volume=b.codec.volume, notices=b.display.notifications;\n        timer_context=true;action();timer_context=false;\n        power::Gate::Instance().locked.store(true);\n        std::function<void()> work;\n        assert(Application::GetInstance().queue.Pop(work));work();\n        assert(b.codec.volume==volume && b.display.notifications==notices);\n        power::Gate::Instance().locked.store(false);\n    }\n    std::puts("Volume callbacks OK:')

replace('main/display/raw_display.cc','if(!power::Locked())power::SleepService::Instance().Toggle();send_command_ack("sleep_queued");','if(!power::Locked()) { power::SleepService::Instance().Toggle(); }\n                        send_command_ack("sleep_queued");')
