#!/usr/bin/env python3
"""Rasterize pinned Lucide SVGs into native 1-bit firmware icons.
Requires Pillow and @resvg/resvg-js 2.6.2. Pass --resvg /path/to/node/module.
"""
import argparse, hashlib, json, subprocess, tempfile
from pathlib import Path
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--resvg',required=True)
args=parser.parse_args()
source=ROOT/'assets/icons/lucide'
metadata=json.loads((source/'source.json').read_text())
for filename,digest in metadata['sha256'].items():
    if hashlib.sha256((source/filename).read_bytes()).hexdigest()!=digest:
        raise SystemExit('Pinned Lucide source changed: '+filename)
names=sorted(path.stem for path in source.glob('*.svg'))
ident=lambda name: ''.join(word.capitalize() for word in name.split('-'))
lines=['// Generated by tools/build_ui_icons.py. Lucide ISC / Feather MIT; see assets/icons/lucide/LICENSE.', '#pragma once', '#include <cstdint>', 'namespace lucide {', 'enum class Id { '+', '.join(map(ident,names))+' };', 'struct Icon { int size, top, bottom; const uint8_t* bits; };']
entries=[]
with tempfile.TemporaryDirectory() as folder:
    for name in names:
        for size in (24,28,32,40):
            png=Path(folder)/'icon.png'
            subprocess.run(['node','-e', 'const fs=require("fs"),{Resvg}=require(process.argv[1]); const svg=fs.readFileSync(process.argv[2],"utf8").replace(/currentColor/g,"black"); fs.writeFileSync(process.argv[3],new Resvg(svg,{fitTo:{mode:"width",value:Number(process.argv[4])},background:"white"}).render().asPng());',args.resvg,str(source/(name+'.svg')),str(png),str(size)],check=True)
            im=Image.open(png).convert('L'); black=[im.getpixel((x,y))<160 for y in range(size) for x in range(size)]
            bits=[sum(int(black[k+j])<<(7-j) for j in range(8)) for k in range(0,len(black),8)]
            rows=[i//size for i,value in enumerate(black) if value]
            symbol=ident(name)+str(size)
            lines.append('inline constexpr uint8_t '+symbol+'[] = {'+','.join(map(str,bits))+'};')
            entries.append('{'+f'{size},{min(rows)},{max(rows)},{symbol}'+'}')
lines+=['inline constexpr Icon icons[] = {'+','.join(entries)+'};','inline const Icon& Get(Id id, int size) {','    const int offset=size==24 ? 0 : size==28 ? 1 : size==32 ? 2 : 3;','    return icons[static_cast<unsigned>(id)*4+offset];','}', '}']
out=ROOT/'main/display/icons/lucide_icons.h';out.parent.mkdir(parents=True,exist_ok=True);out.write_text('\n'.join(lines)+'\n')
print(f'{len(names)} icons, 4 native sizes -> {out}')
